version: '3.8'

services:
    mysql:
        image: mysql:8.0.26
        volumes:
            - ./data/:/var/lib/mysql
            - ./backup/:/docker-entrypoint-initdb.d 
        restart: unless-stopped
        
        environment:
            MYSQL_ROOT_PASSWORD: GAud4mZby8F3SD6P
            MYSQL_DATABASE: employees
            MYSQL_USER: user
            MYSQL_PASSWORD: teste
            
    php:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - "./web:/var/www/html/"
        depends_on:
            - mysql